print("Hello")
print("Welcome to Google Cloud")
print("Welcome to Google Cloud")
print("Welcome to Google Cloud")
print("Welcome to Google Cloud")
print("Welcome to Google Cloud")
print("Welcome to Google Cloud")
print("Welcome to Google Cloud")
print("Welcome to Google Cloud")
